project/app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from app import views 
app_name= 'app'

urlpatterns=[
    path('search/', views.product_search, name='product_search'),
    path('home/',views.home,name='home'),
    path('reg/',views.signup,name='signup'),
    path('',views.signin,name='signin'),
    path('logout/',views.signout,name='signout'),
   

    path('<slug:c_slug>/',views.home,name='products_by_category'),
    path("detail/<int:id>/",views.detail,name='detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('cartdetail/<int:id>/', views.cart_detail, name='cart_detail'),  
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('forgot_password',views.forgtpss,name='forgot_password'),
    path('payment/<int:id>/',views.payment,name='payment'),
    path('success',views.home1,name='success'),
    path('payment/<int:id>/success', views.payment_success, name='payment_success'),
    path('payment_request/', views.payment_request, name='payment_request'),  # For OTP generation and initial payment request
    path('otp-verification/', views.otp_verification, name='otp_verification'),  # For OTP verification page





] 

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Include Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- Include Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- Include Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <!-- Include Font Awesome for Icons -->
    <script src="https://kit.fontawesome.com/8b8ca58c15.js" crossorigin="anonymous"></script>
    
    <!-- Meta Description and Title -->
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}GOSHOP{% endblock %}</title>
    <style>
       
          .navbar {
        background-color: black; /* Navbar background color */
        padding: 10px;
        position: -webkit-sticky; /* Safari support */
        position: sticky; /* Make navbar sticky */
        top: 0; /* Navbar will stick to the top of the page */
        z-index: 1030; /* Ensure navbar stays on top of other content */
    }

    .nav-link {
        color: black !important; /* Default text color, always black */
        font-size: 18px; /* Adjust font size */
        text-decoration: none; /* Remove underline if any */
    }

    .nav-link:hover {
        color: black !important; /* Keep text color black on hover */
    }

    .nav-link i {
        color: black !important; /* Default color for all icons */
    }

    .nav-link i:hover {
        color: black !important; /* Keep icon color black on hover */
    }


    </style>
</head>

<body>
<div>
      <!-- Header -->
     
      <div class="social-icons d-flex" style="background-color:green;">
        <a href="https://www.facebook.com" target="_blank"  style="padding-left:1195px;color: black ;"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.twitter.com" target="_blank" style="padding-left:20px; color: black;"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com" target="_blank" style="padding-left:20px; color: black;"><i class="fab fa-instagram"></i></a>
      </div>


      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">

        <div class="container-fluid">
          <!-- Logo -->
          <a href="{% url 'app:home' %}">
            <img src="{% static 'image/Goshop Logo.png' %}" alt="Logo" id="a1">
        </a>
        
          
          <!-- Toggler Button for Mobile View -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <!-- Navbar Content -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <!-- Search Form -->
            <!-- <form class="d-flex ms-auto" role="search" method="GET" action="{% url 'app:product_search' %}">
              <div class="search-container">
                  <input type="text" name="q" placeholder="Search for Products, Brands and More" aria-label="Search">
                  <button type="submit" class="btn btn-outline-secondary search-icon">
                      <i class="fas fa-search"></i>
                  </button>
              </div>
          </form> -->
          
            <form class="d-flex" role="search"  method="GET" action="{% url 'app:product_search' %}">
              <div class="search-container">
                <input type="text"name="q" placeholder="Search for Products, Brands and More" id="a2">
                <i class="fas fa-search"></i>
              </div>
            </form>
      
            <!-- Navbar Links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left: auto;">
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="fas fa-home"></i> Home
                </a>
              </li>
      
              <!-- Account Dropdown -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdownAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownAccount">
                  <li><a class="dropdown-item" href="{% url 'app:signup' %}">Sign Up</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:signin' %}">Sign In</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:signout' %}">Sign Out</a></li>
                </ul>
              </li>
              
              <!-- Shop By Dropdown -->
              <li class="nav-item dropdown {% if 'app' in request.path %} active {% endif %}">
                <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdownShopBy" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-tags"></i> Shop By
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownShopBy">
                  <li><a class="dropdown-item" href="{% url 'app:home' %}">All Products</a></li>
                  {% for cat in links %}
                    <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
      
              <!-- Wishlist and Cart Links -->
              <!-- <li class="nav-item">
                <a class="nav-link text-black" href="#"><i class="fas fa-heart"></i> Wishlist</a>
              </li> -->
              
             <li class="nav-item">
                {% if cart %}
                  <a class="nav-link text-black" href="{% url 'app:cart_detail' cart.id %}">
                {% else %}
                  <a class="nav-link text-black" href="{% url 'app:cart_detail' 0 %}">
                {% endif %}
                  <i class="fas fa-shopping-cart"></i> Cart
                  {% if item_count %}
                    <span class="cart-count">{{ item_count }}</span>
                  {% endif %}
                </a>
              </li>
            
              
              
            </ul>
          </div>
        </div>
      </nav>

  <!-- carousel -->
  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'image/vegetables.jpg' %}" class="d-block w-100" alt="..." style="height: 350px;">
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/electronic.jpg' %}" class="d-block w-100" alt="..." style="height: 350px;">
      </div>
      <!-- <div class="carousel-item">
        <img src="{% static 'image/electronic sale.webp' %}" class="d-block w-100" alt="...">
      </div> -->
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <br>
<div>
  <h1 class="text-center my_title">Our Products Collections</h1>
  <!-- <p class="text-justify">Since Ecommerce Collections are in fact dynamic Collections, adding products and categories is very similar to creating collection items. However, unlike CMS Collections, Ecommerce Collections have a set of default fields that you cannot edit in the Collection schema. Still, you can add custom fields to enrich your Ecommerce Collections. For example, you can add color fields, switch fields, and even a file field where you can upload a catalog of your category or PDF specs of your product.</p> -->
</div>

 <!-- Main Content -->
 <div class="container">
  {% block content %}
  
        <!-- This block will be overridden in child templates -->         
  {% endblock %}
</div>

<!-- footer -->
                      
  

     <section class="abou container-fluid" id="idd" style="background-color: black; width: 100%; height: auto; margin-top: 100px; padding-top: 50px; padding-bottom: 20px;">
      <div class="mai" style="display: flex; justify-content: space-between; color: white; flex-wrap: wrap;">
          <!-- Help Section -->
           <div class="left" style="flex: 1; min-width: 200px; margin-bottom: 20px;">
              <h6 style="color: gray;">HELP</h6>
              <h6>Fees and Payments</h6>
              <h6>Track Order</h6>
              <h6>Returns</h6>
              <h6>Cancellation</h6>
              <h6>FAQ</h6>
              <h6>Terms and Conditions</h6>
          </div> 
      
          <!-- About Us Section -->
           <div class="center" style="flex: 1; min-width: 200px; margin-bottom: 20px;">
              <h6 style="color: gray;">ABOUT US</h6>
              <h6>Contact Us</h6>
              <h6>About Us</h6>
              <h6>Our Vision And Purpose</h6>
              <h6>Quality Standards</h6>
              <h6>Available Delivery Slot</h6>
              <h6>Privacy Policy</h6>
          </div>    
          
          <!-- Our Policies Section -->
           <div class="right" style="flex: 1; min-width: 200px;">
              <h6 style="color: gray;">OUR POLICIES</h6>
              <h6>Privacy Policy</h6>
              <h6>Payment Policy</h6>
              <h6>Disclaimer</h6> 
          </div>
          
      </div>
  </section> 
  
  <!-- copyright -->
   <footer class="footer">
    
   </footer>
  
 <div class="copyright-section">
    <p>&copy; 2024 GoShop. All Rights Reserved.</p>
  </div> 

        




</body>
</html>

project/templates/category.html
<!-- {% extends 'nav.html' %}
{% load static %}

{% block content %}
    <style>
        .button {
            padding: 8px 16px; /* Adjusted padding for a smaller button */
            margin: 8px 4px;
            font-size: 14px; /* Slightly smaller font size */
            font-weight: bold;
            border: none;
            cursor: pointer;
            border-radius: 4px;
        }
        .add-to-cart {
            background-color: #28a745; /* Green color */
            color: white;
        }
        .remove {
            background-color: #dc3545; /* Red color */
            color: white;
        }
        .cart-count {
            background-color: red;
            color: white;
            border-radius: 50%;
            padding: 2px 8px;
            font-size: 12px;
            position: absolute; /* Changed to absolute for better control */
            top: -10px;
            right: -10px;
            /* Ensure it's placed correctly relative to the cart icon */
        }
        .container {
            max-width:50px; /* Decreased container width */
            margin: 0 auto;
            padding: 20px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .cart-container {
            display: flex;
            flex-wrap: wrap; /* Allows items to wrap to the next line if necessary */
            gap: 20px; /* Space between items */
            justify-content: center; /* Center items horizontally */
        }
        .cart-item {
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            padding: 10px;
            text-align: center;
            width: calc(50% - 20px); /* Adjust width to fit 2 items per row with gap */
            box-sizing: border-box; /* Include padding and border in the element's total width and height */
        }
        .cart-item img {
            max-width: 200px; /* Smaller image width */
            height: auto;
            border-radius: 8px;
        }
    </style>

    Cart Detail Information
    <h1>Your Cart</h1>
    <p>Total Items in Cart: {{ item_count }}</p>
    
    <!-- Display each cart item -->
    <!-- {% if cart_items %}
        <div class="cart-container">
            {% for item in cart_items %}
                <div class="cart-item">
                    <img src="{{ item.product.image.url }}" alt="Product Image">
                    <p style="font-size: 14px; font-weight: bold;">Name: {{ item.product.name }}</p>
                    <p style="font-size: 14px; font-weight: bold;">Price: ${{ item.product.price }}</p>
                    <p style="font-size: 14px; font-weight: bold;">Quantity: {{ item.quantity }}</p>
                    <form action="{% url 'app:cart_remove' item.product.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="button remove">Remove</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    {% else %} -->
        <!-- <p>Your cart is empty.</p> -->
        <!-- <p class="empty-cart-message">Your cart is empty. Start adding products to see them here!</p>
    {% endif %}
{% endblock %} -->



            <!-- <button class="button remove"><a href="{% url 'app:payment' %}"> Pay Now</a></button> -->

  <!-- payment -->
<!-- 
  {% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>Make Payment</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&family=Pacifico&family=Poppins:wght@300&display=swap"
        rel="stylesheet">
</head>
<style>
    .profile{
        padding-top: 30px;
    }
</style>
<body>

    <div class="profile">
        <div class="container">
            <h1>Make <span style="color:#03c04a;">Payment</span></h1>
            <div class="row">
                <div class="col-md-6">
                    <!-- <img src="{% static '/pay.png' %}" alt="Contact Image" class="img-fluid"> -->
                     <!-- Display the Product Image -->
                <img src="{{ d.image.url }}" alt="{{ product.image }}" class="img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <form action="success" method="post" >
                            {% csrf_token %}
                            <!-- <div class="card-body">   
                                <h5 class="card-title">Service Type: <b>{{ wastetype }}</b></h5>
                                <h5 class="card-title">Total Weight: <b>{{ weight }} kg</b></h5>
                                <h5 class="card-title">Minimum Service Charge: <b>Rs. 100/-</b></h5>
                            </div> -->
                            <!-- <button type="submit" class="btn btn-success ml-4 mb-4">Pay Rupees 100/-</button> -->
                            <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_JAeLcxoJpwFjEq"
                            data-amount="50000" data-currency="INR" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay"
                            data-name="Professional Cipher" data-description="Django and Data Science"
                            data-image="https://example.com/your_logo.jpg" data-prefill.name="PC" data-prefill.email="pc@studygyaan.com"
                            data-theme.color="#F37254"></script>
                
                        </form>
                    </div>
                </div>
            </div>

        </div>


    </div>

    </div>

</body>

</html> -->


<!-- razorpay -->
data-amount="50000" data-currency="INR" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay"




<!-- signup -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f4; 
            font-family: Arial, sans-serif;
            background-image: url("{% static 'image/pink.png' %}"); /* Update the path to your image */
            background-size: cover; 
          
        }
        .auth-container {
            width: 100%;
            max-width: 400px;
            background-color: silver;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            height: 580px;
        }
        .auth-form h2 {
            text-align: center;
            margin-bottom: 20px;
            font-size: 24px;
            color: #333;
        }
        .input-group {
            margin-bottom: 20px;
        }
        .input-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
      
        }
        .input-group input {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 16px;
            /* background-color:#fff; Ensure all inputs have the same background color */
            background-color: #f0f0f0; /* Replace this with the desired color */
        }
        button {
            width: 100%;
            padding: 10px;
            background-color: black;
            color: white;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #333;
        }
        .links {
            margin-top: 20px;
            text-align: center;
        }
        .links a {
            color: #333;
            text-decoration: none;
            font-size: 14px;
        }
        .links a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
  <div class="auth-container">
    <div class="auth-form">
      <h2>CREATE ACCOUNT</h2>
      <form method="POST" action="{% url 'app:signup' %}">
          {% csrf_token %}
        <div class="input-group">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" placeholder="Enter your username" required>
        </div>
        <div class="input-group">
          <label for="email">Email</label>
          <input type="email" id="email" name="email" placeholder="Enter your email" required>
        </div>
        <div class="input-group">
          <label for="password">Password</label>
          <input type="password" id="password" name="password" placeholder="Enter your password" required>
          
        </div>
        <div class="input-group">
          <label for="confirm_password">Confirm Password</label>
          <input type="password" id="confirmpassword" name="confirmpassword" placeholder="Confirm your password" required>
          

        </div>
        <button type="submit">SUBMIT</button>
        <div class="links">
          <a href="{% url 'app:signin' %}">Already have an account? Sign In</a>
        </div>
      </form>
    </div>
  </div>
</body>
</html>

project/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Include Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- Include Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- Include Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <!-- Include Font Awesome for Icons -->
    <script src="https://kit.fontawesome.com/8b8ca58c15.js" crossorigin="anonymous"></script>
    
    <!-- Meta Description and Title -->
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}GOSHOP{% endblock %}</title>
    <style>
          .navbar {
        background-color: black; /* Navbar background color */
        padding: 10px;
        position: -webkit-sticky; /* Safari support */
        position: sticky; /* Make navbar sticky */
        top: 0; /* Navbar will stick to the top of the page */
        z-index: 1030; /* Ensure navbar stays on top of other content */
    }

    .nav-link {
        color: black !important; /* Default text color, always black */
        font-size: 18px; /* Adjust font size */
        text-decoration: none; /* Remove underline if any */
    }

    .nav-link:hover {
        color: black !important; /* Keep text color black on hover */
    }

    .nav-link i {
        color: black !important; /* Default color for all icons */
    }

    .nav-link i:hover {
        color: black !important; /* Keep icon color black on hover */
    }


    </style>
</head>

<body>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">

        <div class="container-fluid">
          <!-- Logo -->
          <a href="{% url 'app:home' %}">
            <img src="{% static 'image/Goshop Logo.png' %}" alt="Logo" id="a1">
        </a>
        
          
          <!-- Toggler Button for Mobile View -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <!-- Navbar Content -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <!-- Search Form -->
            <form class="d-flex" role="search">
              <div class="search-container">
                <input type="text" placeholder="Search for Products, Brands and More" id="a2">
                <i class="fas fa-search search-icon"></i>
              </div>
            </form>
      
            <!-- Navbar Links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left: auto;">
              <li class="nav-item">
                <a href="{% url 'app:home' %}" class="nav-link">
                  <i class="fas fa-home"></i> Home
                </a>
              </li>
      
              <!-- Account Dropdown -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdownAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i> Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownAccount">
                  <li><a class="dropdown-item" href="{% url 'app:signup' %}">Sign Up</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:signin' %}">Sign In</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:signout' %}">Sign Out</a></li>
                </ul>
              </li>
              
              <!-- Shop By Dropdown -->
              <li class="nav-item dropdown {% if 'app' in request.path %} active {% endif %}">
                <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdownShopBy" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-tags"></i> Shop By
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownShopBy">
                  <li><a class="dropdown-item" href="{% url 'app:home' %}">All Products</a></li>
                  {% for cat in links %}
                    <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
      
              <!-- Wishlist and Cart Links -->
              <!-- <li class="nav-item">
                <a class="nav-link text-black" href="#"><i class="fas fa-heart"></i> Wishlist</a>
              </li> -->

              <!-- <li class="nav-item">
                {% if item_count %}
                    <a class="nav-link text-black" href="{% url 'app:cart_detail' cart.id %}">
                        <i class="fas fa-shopping-cart"></i> Cart
                        <span class="cart-count">{{ item_count }}</span>
                    </a>
                {% else %}
                    <a class="nav-link text-black" href="{% url 'app:cart_detail' 0 %}">
                        <i class="fas fa-shopping-cart"></i> Cart
                    </a>
                {% endif %}
            </li> -->
              
            </ul>
          </div>
        </div>
      </nav>
       {% block content %}
  
        <!-- This block will be overridden in child templates -->         
  {% endblock %}
</body>
</html>